export const QUESTION_TYPES = {
	MULTIPLE_CHOICE: "MULTIPLE_CHOICE",
	IMAGE_ZONES: "IMAGE_ZONES",
	TRUE_FALSE: "TRUE_FALSE",
	SHORT_ANSWER: "SHORT_ANSWER",
} as const

export const RESOURCE_TYPES = {
	VIDEO: "VIDEO",
	PRESENTATION: "PRESENTATION",
	DOCUMENT: "DOCUMENT",
} as const
